Config = {}

Config.Currency = '€'

-- If you experience issues with your zones not working, please ensure the Z value of your vec3 points match. Using different heights may cause problems.

---@type ZoneOptions[]
Config.Zones = {
-- These MUST be configured with your own location before using them. The current coordinates are set for MOLO MRPD and Benny's
--     {
--         freeRepair = { 'police' },
--         freeMods = { 'police' },
--         job = { 'police' },
--         hideBlip = true,
--         points = {
--             vec3(455.15, -991.55, 25.75),
--             vec3(444.83, -991.55, 25.75),
--             vec3(444.84, -1000.55, 25.75),
--             vec3(455.13, -1000.56, 25.75),
--         }
--     },
--     {
--         freeRepair = { 'police' },
--         freeMods = { 'ambulance' },
--         points = {
--             vec3(-344.36, -121.92, 38.60),
--             vec3(-319.43, -130.65, 38.60),
--             vec3(-324.77, -147.93, 38.60),
--             vec3(-348.59, -139.1, 38.60),
--         }
--     },
    {
        points = {
            vec3(-224.97, -1314.69, 30.89),
            vec3(-225.63, -1339.28, 30.89),
            vec3(-191.95, -1339.87, 30.89),
            vec3(-192.85, -1314.59, 30.89),
        }
    },
    {
        points = {
            vec3(-1405.72, -445.51, 34.48),
            vec3(-1427.71, -460.16, 34.48),
            vec3(-1434.71, -449.5, 34.48),
            vec3(-1411.64, -435.57, 34.48),
        }
    },
    {
        points = {
            vec3(1171.9, 2635.58, 37.77),
            vec3(1171.87, 2644.71, 37.77),
            vec3(1189.76, 2644.09, 37.77),
            vec3(1189.77, 2636.05, 37.77),
        }
    },
    {
        points = {
            vec3(96.74, 6619.63, 31.79),
            vec3(102.72, 6613.48, 31.79),
            vec3(116.01, 6625.49, 31.79),
            vec3(109.59, 6632.11, 31.79),
        }
    }
}

Config.Mods = {
    { id = 0,  label = 'Spoiler',              category = 'parts' },
    { id = 1,  label = 'Voorbumper',         category = 'parts' },
    { id = 2,  label = 'Achterbumper',          category = 'parts' },
    { id = 3,  label = 'Side Skirt',           category = 'parts' },
    { id = 4,  label = 'Uitlaat',              category = 'parts' },
    { id = 5,  label = 'Rolkooi',            category = 'parts' },
    { id = 6,  label = 'Grill',               category = 'parts' },
    { id = 7,  label = 'Hood',                 category = 'parts' },
    { id = 8,  label = 'Linker spatbord',          category = 'parts' },
    { id = 9,  label = 'Rechter spatbord',         category = 'parts' },
    { id = 10, label = 'Dak',                 category = 'parts' },
    { id = 11, label = 'Motor Upgrade',       category = 'performance' },
    { id = 12, label = 'Rem Upgrade',        category = 'performance' },
    { id = 13, label = 'Transmissie Upgrade', category = 'performance' },
    { id = 14, label = 'Toeters',                category = 'parts' },
    { id = 15, label = 'Suspensie Upgrade',   category = 'performance' },
    { id = 16, label = 'Armor Upgrade',        category = 'performance', enabled = true },
    { id = 17, label = 'Nitro',              category = 'performance', enabled = false },
    -- { id = 18, label = 'Turbo Upgrade', category = 'performance' },
    { id = 19, label = 'Subwoofer',            category = 'parts' },
    -- { id = 20, label = 'Tyre smoke',                category = 'colors' },
    { id = 21, label = 'Hydraulics',           category = 'parts' },
    -- { id = 22, label = 'Xenon lights',         category = 'colors' },
    -- { id = 23, label = 'Wheels', category = 'parts' },
    -- { id = 24, label = 'Rear wheels or hydraulics', category = 'parts' },
    { id = 25, label = 'Plaathouder',         category = 'parts' },
    { id = 26, label = 'Vanity Plates',        category = 'parts' },
    { id = 27, label = 'Trim A',               category = 'parts' },
    { id = 28, label = 'Ornaments',            category = 'parts' },
    { id = 29, label = 'Dashboard',            category = 'parts' },
    { id = 30, label = 'Dial',                 category = 'parts' },
    { id = 31, label = 'Deur Speaker',         category = 'parts' },
    { id = 32, label = 'Zitplaatsen',                category = 'parts' },
    { id = 33, label = 'Stuur',       category = 'parts' },
    { id = 34, label = 'Versnellingshendel',       category = 'parts' },
    { id = 35, label = 'Plaque',               category = 'parts' },
    { id = 36, label = 'Speaker',              category = 'parts' },
    { id = 37, label = 'Koffer',                category = 'parts' },
    { id = 38, label = 'Hydraulic',            category = 'parts' },
    { id = 39, label = 'Motor Blok',         category = 'parts' },
    { id = 40, label = 'Lucht Filter',           category = 'parts' },
    { id = 41, label = 'Stut',                category = 'parts' },
    { id = 42, label = 'Arch Cover',           category = 'parts' },
    { id = 43, label = 'Aerial',               category = 'parts' },
    { id = 44, label = 'Trim B',               category = 'parts' },
    { id = 45, label = 'Benzinetank',            category = 'parts' },
    { id = 46, label = 'Linker deur',            category = 'parts' },
    { id = 47, label = 'Rechter deur',           category = 'parts' },
    -- { id = 48, label = 'Livery',               category = 'colors' },
    { id = 49, label = 'Lichtbalk',             category = 'parts' },
}

Config.Horns = {
    { id = 0,  label = 'Truck Horn' },
    { id = 1,  label = 'Cop Horn' },
    { id = 2,  label = 'Clown Horn' },
    { id = 3,  label = 'Musical Horn 1' },
    { id = 4,  label = 'Musical Horn 2' },
    { id = 5,  label = 'Musical Horn 3' },
    { id = 6,  label = 'Musical Horn 4' },
    { id = 7,  label = 'Musical Horn 5' },
    { id = 8,  label = 'Sad Trombone' },
    { id = 9,  label = 'Classical Horn 1' },
    { id = 10, label = 'Classical Horn 2' },
    { id = 11, label = 'Classical Horn 3' },
    { id = 12, label = 'Classical Horn 4' },
    { id = 13, label = 'Classical Horn 5' },
    { id = 14, label = 'Classical Horn 6' },
    { id = 15, label = 'Classical Horn 7' },
    { id = 16, label = 'Scale - Do' },
    { id = 17, label = 'Scale - Re' },
    { id = 18, label = 'Scale - Mi' },
    { id = 19, label = 'Scale - Fa' },
    { id = 20, label = 'Scale - Sol' },
    { id = 21, label = 'Scale - La' },
    { id = 22, label = 'Scale - Ti' },
    { id = 23, label = 'Scale - Do' },
    { id = 24, label = 'Jazz Horn 1' },
    { id = 25, label = 'Jazz Horn 2' },
    { id = 26, label = 'Jazz Horn 3' },
    { id = 27, label = 'Jazz Horn Loop' },
    { id = 28, label = 'Star Spangled Banner 1' },
    { id = 29, label = 'Star Spangled Banner 2' },
    { id = 30, label = 'Star Spangled Banner 3' },
    { id = 31, label = 'Star Spangled Banner 4' },
    { id = 32, label = 'Classical Horn 8 Loop' },
    { id = 33, label = 'Classical Horn 9 Loop' },
    { id = 34, label = 'Classical Horn 10 Loop' },
    { id = 35, label = 'Classical Horn 8' },
    { id = 36, label = 'Classical Horn 9' },
    { id = 37, label = 'Classical Horn 10' },
    { id = 38, label = 'Funeral Loop' },
    { id = 39, label = 'Funeral' },
    { id = 40, label = 'Spooky Loop' },
    { id = 41, label = 'Spooky' },
    { id = 42, label = 'San Andreas Loop' },
    { id = 43, label = 'San Andreas' },
    { id = 44, label = 'Liberty City Loop' },
    { id = 45, label = 'Liberty City' },
    { id = 46, label = 'Festive 1 Loop' },
    { id = 47, label = 'Festive 1' },
    { id = 48, label = 'Festive 2 Loop' },
    { id = 49, label = 'Festive 2' },
    { id = 50, label = 'Festive 3 Loop' },
    { id = 51, label = 'Festive 3' },
    { id = 52, label = 'Air Horn Low Loop' },
    { id = 53, label = 'Air Horn Low' },
    { id = 54, label = 'Air Horn Medium Loop' },
    { id = 55, label = 'Air Horn Medium' },
    { id = 56, label = 'Air Horn High Loop' },
    { id = 57, label = 'Air Horn High' },
}

-- https://docs.fivem.net/natives/?_0x4F1D4BE3A7F24601
Config.Paints = {
    Classic = {
        { id = 0,   label = 'Zwart' },
        { id = 1,   label = 'Grafiet' },
        { id = 2,   label = 'Zwart staal' },
        { id = 3,   label = 'Donker staal' },
        { id = 4,   label = 'Zilver' },
        { id = 5,   label = 'Blauwachtig zilver' },
        { id = 6,   label = 'Gewalst staal' },
        { id = 7,   label = 'Schaduw Zilver' },
        { id = 8,   label = 'Steen Zilver' },
        { id = 9,   label = 'Middernacht zilver' },
        { id = 10,  label = 'Gietijzer zilver' },
        { id = 11,  label = 'Antraciet Zwart' },
        { id = 27,  label = 'Rood' },
        { id = 28,  label = 'Torino Rood' },
        { id = 29,  label = 'Formule rood' },
        { id = 30,  label = 'Blaas rood' },
        { id = 31,  label = 'Grace Rood' },
        { id = 32,  label = 'Granaat Rood' },
        { id = 33,  label = 'Zonsondergang rood' },
        { id = 34,  label = 'Cabernetrood' },
        { id = 35,  label = 'Snoep Rood' },
        { id = 36,  label = 'Zonsopgang Oranje' },
        { id = 38,  label = 'Oranje' },
        { id = 49,  label = 'Donkergroen' },
        { id = 50,  label = 'Racegroen' },
        { id = 51,  label = 'Zee groen' },
        { id = 52,  label = 'Olijfgroen' },
        { id = 53,  label = 'Fel groen' },
        { id = 54,  label = 'Benzine Groen' },
        { id = 61,  label = 'Melkwegblauw' },
        { id = 62,  label = 'Donkerblauw' },
        { id = 63,  label = 'Saksisch Blauw' },
        { id = 64,  label = 'Blauw' },
        { id = 65,  label = 'Mariner blauw' },
        { id = 66,  label = 'Haven blauw' },
        { id = 67,  label = 'Diamant Blauw' },
        { id = 68,  label = 'Surfblauw' },
        { id = 69,  label = 'Nautisch blauw' },
        { id = 70,  label = 'Ultrablauw' },
        { id = 71,  label = 'Schafer Paars' },
        { id = 72,  label = 'Spinnaker Paars' },
        { id = 73,  label = 'Raceblauw' },
        { id = 74,  label = 'Lichtblauw' },
        { id = 88,  label = 'Geel' },
        { id = 89,  label = 'Ras Geel' },
        { id = 90,  label = 'Bronzen' },
        { id = 91,  label = 'Dauw geel' },
        { id = 92,  label = 'Limoen groen' },
        { id = 94,  label = 'Feltzer Bruin' },
        { id = 95,  label = 'Creeen Bruin' },
        { id = 96,  label = 'Chocolade bruin' },
        { id = 97,  label = 'Esdoorn Bruin' },
        { id = 98,  label = 'Zadelbruin' },
        { id = 99,  label = 'Gebleekt bruin' },
        { id = 100, label = 'Mos Bruin' },
        { id = 101, label = 'Bizon Bruin' },
        { id = 102, label = 'Houtbeuk Bruin' },
        { id = 103, label = 'Beukenhout Bruin' },
        { id = 104, label = 'Sienna Bruin' },
        { id = 105, label = 'Zandbruin' },
        { id = 106, label = 'Gebleekt bruin' },
        { id = 107, label = 'Room' },
        { id = 111, label = 'IJswit' },
        { id = 112, label = 'Vorst Wit' },
        { id = 135, label = 'Felroze' },
        { id = 136, label = 'Zalm roze' },
        { id = 137, label = 'Pfister Roze' },
        { id = 138, label = 'Fel oranje' },
        { id = 141, label = 'Middernacht blauw' },
        { id = 142, label = 'Middernacht paars' },
        { id = 143, label = 'Wijn rood' },
        { id = 145, label = 'Helder paars' },
        { id = 147, label = 'Carbon zwart' },
        { id = 150, label = 'Lava Rood' },
    },
    Matte = {
        { id = 12,  label = 'Zwart' },
        { id = 13,  label = 'Grijs' },
        { id = 14,  label = 'Lichtgrijs' },
        { id = 39,  label = 'Rood' },
        { id = 40,  label = 'Donkerrood' },
        { id = 41,  label = 'Oranje' },
        { id = 42,  label = 'Geel' },
        { id = 55,  label = 'Limoen groen' },
        { id = 82,  label = 'Donkerblauw' },
        { id = 83,  label = 'Blauw' },
        { id = 84,  label = 'Middernacht blauw' },
        { id = 131, label = 'IJswit' },
        { id = 148, label = 'Schafer Paars' },
        { id = 149, label = 'Middernacht paars' },
        { id = 151, label = 'Bos Groen' },
        { id = 152, label = 'Olijf Darb' },
        { id = 153, label = 'Donkere aarde' },
        { id = 154, label = 'Woestijn Tan' },
        { id = 155, label = 'Gebladert Groen' },
    },
    Metal = {
        { id = 117, label = 'Geborsteld staal' },
        { id = 118, label = 'Geborsteld zwart staal' },
        { id = 119, label = 'Geborsteld aluminium' },
        { id = 120, label = 'Chroom', },
        { id = 158, label = 'Puur goud' },
        { id = 159, label = 'Geborsteld goud' },
    },
    Worn = {
        { id = 21,  label = 'Zwart' },
        { id = 22,  label = 'Grafiet' },
        { id = 23,  label = 'Zilver grijs' },
        { id = 24,  label = 'Zilver' },
        { id = 25,  label = 'Blauw zilver' },
        { id = 26,  label = 'Schaduw Zilver' },
        { id = 46,  label = 'Rood' },
        { id = 47,  label = 'Goud Rood' },
        { id = 48,  label = 'Donkerrood' },
        { id = 58,  label = 'Donkergroen' },
        { id = 59,  label = 'Groente' },
        { id = 60,  label = 'Zee wassen' },
        { id = 85,  label = 'Donkerblauw' },
        { id = 86,  label = 'Blauw' },
        { id = 87,  label = 'Lichtblauw' },
        { id = 113, label = 'Honingbeige' },
        { id = 114, label = 'Bruin' },
        { id = 115, label = 'Donker bruin' },
        { id = 116, label = 'strobeige' },
        { id = 121, label = 'Gebroken wit' },
        { id = 123, label = 'Oranje' },
        { id = 124, label = 'Lichtoranje' },
        { id = 126, label = 'Taxi geel' },
        { id = 130, label = 'Oranje' },
        { id = 132, label = 'Wit' },
        { id = 133, label = 'Olijf Leger Groen' },
    },
    Chameleon = {
        { id = 161, label = 'Geanodiseerde rode parel' },
        { id = 162, label = 'Geanodiseerde wijnparel' },
        { id = 163, label = 'Geanodiseerde paarse parel' },
        { id = 164, label = 'Geanodiseerde blauwe parel' },
        { id = 165, label = 'Geanodiseerde groene parel' },
        { id = 166, label = 'Geanodiseerde limoenparel' },
        { id = 167, label = 'Geanodiseerde koperen parel' },
        { id = 168, label = 'Geanodiseerde bronzen parel' },
        { id = 169, label = 'Geanodiseerde champagneparel' },
        { id = 170, label = 'Geanodiseerde gouden parel' },
        { id = 171, label = 'Groen/Blauwe klep' },
        { id = 172, label = 'Groen/rode klep' },
        { id = 173, label = 'Groen/bruine klep' },
        { id = 174, label = 'Groen/turquoise klep' },
        { id = 175, label = 'Groene/paarse flip' },
        { id = 176, label = 'Blauwgroen/paarse flip' },
        { id = 177, label = 'Turkoois/rode klep' },
        { id = 178, label = 'Turkoois/paarse klep' },
        { id = 179, label = 'Cyaan/paarse omslag' },
        { id = 180, label = 'Blauw/roze flip' },
        { id = 181, label = 'Blauw/Groene klep' },
        { id = 182, label = 'Paars/rode klep' },
        { id = 183, label = 'Paars/groene klep' },
        { id = 184, label = 'Magenta/groene omslag' },
        { id = 185, label = 'Magenta/gele omslag' },
        { id = 186, label = 'Bordeaux/Groene klep' },
        { id = 187, label = 'Magenta/cyaan omdraaien' },
        { id = 188, label = 'Koper/paarse klep' },
        { id = 189, label = 'Magenta/oranje omslag' },
        { id = 190, label = 'Rood/oranje klep' },
        { id = 191, label = 'Oranje/paarse flip' },
        { id = 192, label = 'Oranje/blauwe klep' },
        { id = 193, label = 'Wit/paarse klep' },
        { id = 194, label = 'Rood/regenboogomslag' },
        { id = 195, label = 'Blauw/regenboog flip' },
        { id = 196, label = 'Donkergroene parel' },
        { id = 197, label = 'Donkerblauwgroen parel' },
        { id = 198, label = 'Donkerblauwe parel' },
        { id = 199, label = 'Donkerpaarse parel' },
        { id = 200, label = 'Olievlek parel' },
        { id = 201, label = 'Lichtgroene parel' },
        { id = 202, label = 'Lichtblauwe parel' },
        { id = 203, label = 'Lichtpaarse parel' },
        { id = 204, label = 'Lichtroze parel' },
        { id = 205, label = 'Gebroken witte parel' },
        { id = 206, label = 'Leuke roze parel' },
        { id = 207, label = 'Babygele parel' },
        { id = 208, label = 'Babygroene parel' },
        { id = 209, label = 'Babyblauwe parel' },
        { id = 210, label = 'Crème Parel' },
        { id = 211, label = 'Witte prismatische parel' },
        { id = 212, label = 'Grafiet prismatische parel' },
        { id = 213, label = 'Blauwe prismatische parel' },
        { id = 214, label = 'Paarse prismatische parel' },
        { id = 215, label = 'Hete roze prismatische parel' },
        { id = 216, label = 'Rode prismatische parel' },
        { id = 217, label = 'Groene prismatische parel' },
        { id = 218, label = 'Zwarte prismatische parel' },
        { id = 219, label = 'Olieramp Prismatische parel' },
        { id = 220, label = 'Regenboog prismatische parel' },
        { id = 221, label = 'Zwarte holografische parel' },
        { id = 222, label = 'Witte holografische parel' },
        { id = 223, label = 'Oosterdam Specials: Monochroom' },
        { id = 224, label = 'Oosterdam Specials: dag en nacht' },
        { id = 225, label = 'Oosterdam Specials: De verliezer' },
        { id = 226, label = 'Oosterdam Specials: De verliezer' },
        { id = 227, label = 'Oosterdam Specials: Vice City' },
        { id = 228, label = 'Oosterdam Specials: Synthwave-avond' },
        { id = 229, label = 'Oosterdam Specials: vier seizoenen' },
        { id = 230, label = 'Oosterdam Specials: M9 Throwback' },
        { id = 231, label = 'Oosterdam Specials: Bubblegum' },
        { id = 232, label = 'Oosterdam Specials: Volledige regenboog' },
        { id = 233, label = 'Oosterdam Specials: Zonsondergang' },
        { id = 234, label = 'Oosterdam Specials: Tee Gezien' },
        { id = 235, label = 'Oosterdam Specials: Kamen Rider' },
        { id = 236, label = 'Oosterdam Specials: Chromatisch' },
        { id = 237, label = 'Oosterdam Specials: Het is Kerstmis!' },
        { id = 238, label = 'Oosterdam Specials: Temp peratre' },
        { id = 239, label = 'Oosterdam Specials: HSW-badge' },
        { id = 240, label = 'Oosterdam Specials: Anod. Bliksem' },
        { id = 241, label = 'Oosterdam Specials: Emeralds' },
        { id = 242, label = 'Oosterdam Specials: Fubuki Kaste' },
    }
}

Config.ModLabels = {
    [11] = { -- Engine
        { id = -1, label = 'Stock' },
        { id = 0,  label = 'Motor 1' },
        { id = 1,  label = 'Motor 2' },
        { id = 2,  label = 'Motor 3' },
        { id = 3,  label = 'Motor 4' },
    },
    [12] = { -- Brake
        { id = -1, label = 'Stock' },
        { id = 0,  label = 'Remmen 1' },
        { id = 1,  label = 'Remmen 2' },
        { id = 2,  label = 'Remmen 3' },
    },
    [13] = { -- Transmission
        { id = -1, label = 'Stock' },
        { id = 0,  label = 'Transmissie 1' },
        { id = 1,  label = 'Transmissie 2' },
        { id = 2,  label = 'Transmissie 3' },
        { id = 3,  label = 'Transmissie 4' },
    },
    [14] = { -- Horn
        { id = 0,  label = 'Truck Horn' },
        { id = 1,  label = 'Cop Horn' },
        { id = 2,  label = 'Clown Horn' },
        { id = 3,  label = 'Musical Horn 1' },
        { id = 4,  label = 'Musical Horn 2' },
        { id = 5,  label = 'Musical Horn 3' },
        { id = 6,  label = 'Musical Horn 4' },
        { id = 7,  label = 'Musical Horn 5' },
        { id = 8,  label = 'Sad Trombone' },
        { id = 9,  label = 'Classical Horn 1' },
        { id = 10, label = 'Classical Horn 2' },
        { id = 11, label = 'Classical Horn 3' },
        { id = 12, label = 'Classical Horn 4' },
        { id = 13, label = 'Classical Horn 5' },
        { id = 14, label = 'Classical Horn 6' },
        { id = 15, label = 'Classical Horn 7' },
        { id = 16, label = 'Scale - Do' },
        { id = 17, label = 'Scale - Re' },
        { id = 18, label = 'Scale - Mi' },
        { id = 19, label = 'Scale - Fa' },
        { id = 20, label = 'Scale - Sol' },
        { id = 21, label = 'Scale - La' },
        { id = 22, label = 'Scale - Ti' },
        { id = 23, label = 'Scale - Do' },
        { id = 24, label = 'Jazz Horn 1' },
        { id = 25, label = 'Jazz Horn 2' },
        { id = 26, label = 'Jazz Horn 3' },
        { id = 27, label = 'Jazz Horn Loop' },
        { id = 28, label = 'Star Spangled Banner 1' },
        { id = 29, label = 'Star Spangled Banner 2' },
        { id = 30, label = 'Star Spangled Banner 3' },
        { id = 31, label = 'Star Spangled Banner 4' },
        { id = 32, label = 'Classical Horn 8 Loop' },
        { id = 33, label = 'Classical Horn 9 Loop' },
        { id = 34, label = 'Classical Horn 10 Loop' },
        { id = 35, label = 'Classical Horn 8' },
        { id = 36, label = 'Classical Horn 9' },
        { id = 37, label = 'Classical Horn 10' },
        { id = 38, label = 'Funeral Loop' },
        { id = 39, label = 'Funeral' },
        { id = 40, label = 'Spooky Loop' },
        { id = 41, label = 'Spooky' },
        { id = 42, label = 'San Andreas Loop' },
        { id = 43, label = 'San Andreas' },
        { id = 44, label = 'Liberty City Loop' },
        { id = 45, label = 'Liberty City' },
        { id = 46, label = 'Festive 1 Loop' },
        { id = 47, label = 'Festive 1' },
        { id = 48, label = 'Festive 2 Loop' },
        { id = 49, label = 'Festive 2' },
        { id = 50, label = 'Festive 3 Loop' },
        { id = 51, label = 'Festive 3' },
        { id = 52, label = 'Air Horn Low Loop' },
        { id = 53, label = 'Air Horn Low' },
        { id = 54, label = 'Air Horn Medium Loop' },
        { id = 55, label = 'Air Horn Medium' },
        { id = 56, label = 'Air Horn High Loop' },
        { id = 57, label = 'Air Horn High' },
    },
    [15] = { -- Suspension
        { id = -1, label = 'Stock' },
        { id = 0,  label = 'Suspensie 1' },
        { id = 1,  label = 'Suspensie 2' },
        { id = 2,  label = 'Suspensie 3' },
        { id = 3,  label = 'Suspensie 4' },
        { id = 4,  label = 'Suspensie 5' },
    },
    [16] = { -- Armor
        { id = -1, label = 'Stock' },
        { id = 0,  label = 'Armor 1' },
        { id = 1,  label = 'Armor 2' },
        { id = 2,  label = 'Armor 3' },
        { id = 3,  label = 'Armor 4' },
        { id = 4,  label = 'Armor 5' },
    },
}

Config.Xenon = {
    { id = -1, label = 'Standaard' },
    { id = 0,  label = 'Wit' },
    { id = 1,  label = 'Blauw' },
    { id = 2,  label = 'Elektrisch blauw' },
    { id = 3,  label = 'Muntgroen' },
    { id = 4,  label = 'Limoen groen' },
    { id = 5,  label = 'Geel' },
    { id = 6,  label = 'Gouden douche' },
    { id = 7,  label = 'Oranje' },
    { id = 8,  label = 'Rood' },
    { id = 9,  label = 'Ponyroze' },
    { id = 10, label = 'Felroze' },
    { id = 11, label = 'Paars' },
    { id = 12, label = 'Blacklight' },
}

Config.WindowTints = {
    { id = 0, label = 'Geen' },
    { id = 1, label = 'Puur zwart' },
    { id = 2, label = 'Donkere rook' },
    { id = 3, label = 'Lichte rook' },
    { id = 4, label = 'Stock' },
    { id = 5, label = 'Groen' },
}

Config.PlateIndexes = {
    { id = 0, label = 'Blauw op wit 1' },
    { id = 1, label = 'Geel op zwart' },
    { id = 2, label = 'Geel op Blauw' },
    { id = 3, label = 'Blauw op Wit 2' },
    { id = 4, label = 'Blauw op Wit 3' },
    { id = 5, label = 'Yankton' },
}

Config.Neon = {
    { id = 0, label = 'Links' },
    { id = 1, label = 'Rechts' },
    { id = 2, label = 'Voor' },
    { id = 3, label = 'Achter' },
}

Config.NeonColors = {
    { label = 'Wit',         r = 222, g = 222, b = 255 },
    { label = 'Blauw',          r = 2,   g = 21,  b = 255 },
    { label = 'Elektrisch blauw', r = 3,   g = 83,  b = 255 },
    { label = 'Muntgroen',    r = 0,   g = 255, b = 140 },
    { label = 'Limoen groen',    r = 94,  g = 255, b = 1 },
    { label = 'Geel',        r = 255, g = 255, b = 0 },
    { label = 'Gouden douche', r = 255, g = 150, b = 0 },
    { label = 'Oranje',        r = 255, g = 62,  b = 0 },
    { label = 'Rood',           r = 255, g = 1,   b = 1 },
    { label = 'Ponyroze',     r = 255, g = 50,  b = 100 },
    { label = 'Felroze',      r = 255, g = 5,   b = 190 },
    { label = 'Paars',        r = 35,  g = 1,   b = 255 },
    { label = 'Blacklight',    r = 15,  g = 3,   b = 255 },
}

Config.TyreSmoke = {
    { label = "Witte rook",  r = 254, g = 254, b = 254 },
    { label = "Zwarte rook",  r = 1,   g = 1,   b = 1 },
    { label = "Blauwe Rook",   r = 0,   g = 150, b = 255 },
    { label = "Gele rook", r = 255, g = 255, b = 50 },
    { label = "Oranje Rook", r = 255, g = 153, b = 51 },
    { label = "Rode Rook",    r = 255, g = 10,  b = 10 },
    { label = "Groene Rook",  r = 10,  g = 255, b = 10 },
    { label = "Paarse rook", r = 153, g = 10,  b = 153 },
    { label = "Roze rook",   r = 255, g = 102, b = 178 },
    { label = "Grijze Rook",   r = 128, g = 128, b = 128 }
}

Config.Wheels = {
    {
        id = 0,
        label = 'Sport',
    },
    {
        id = 1,
        label = 'Muscle',
    },
    {
        id = 2,
        label = 'Lowrider',
    },
    {
        id = 3,
        label = 'Suv',
    },
    {
        id = 4,
        label = 'Offroad',
    },
    {
        id = 5,
        label = 'Tuner',
    },
    {
        id = 6,
        label = 'Bike front wheel',
    },
    {
        id = 7,
        label = 'Hiend',
    },
    {
        id = 8,
        label = "Benny's Original",
    },
    {
        id = 9,
        label = "Benny's Bespoke",
    },
    {
        id = 10,
        label = 'Open Wheel',
    },
    {
        id = 11,
        label = 'Street',
    },
    {
        id = 12,
        label = 'Track',
    },
}

Config.Prices = {
    ['cosmetic'] = 500,
    ['colors'] = 1000,
    [11] = { 0, 0.1, 0.2, 0.3, 0.4 },     -- Engine
    [12] = { 0, 0.1, 0.2, 0.3 },               -- Brakes
    [13] = { 0, 0.1, 0.2, 0.3, 0.4 },      -- Transmission
    [15] = { 0, 0.1, 0.2, 0.3, 0.4, 0.5 }, -- Suspension
    [16] = { 0, 0.1, 0.2, 0.3, 0.4, 1.5},      -- Armor
    [18] = 0.3                                  -- Turbo
}
